# Generated by Django 5.0.7 on 2024-07-25 08:22

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name='admin'),
        Group(name='procurement'),
        Group(name='cashier'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]