# Generated by Django 5.2.4 on 2025-08-25 04:35

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    
    # Use get_or_create to avoid duplication if rerun
    groups = ['admin', 'procurement', 'cashier']
    for name in groups:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
