# Generated by Django 5.2.5 on 2025-11-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
