# Generated by Django 5.2.4 on 2025-08-15 03:38

import suppliers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(default=suppliers.models.generate_incremental_code, editable=False, max_length=10, unique=True),
        ),
    ]
