# Generated by Django 5.2.4 on 2025-08-20 06:46

import suppliers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(default=suppliers.models.generate_incremental_code, max_length=10, unique=True),
        ),
    ]
