# Generated by Django 5.2.9 on 2026-01-15 08:49

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashier_books', '0001_initial'),
        ('coupons', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('sub_total', models.BigIntegerField()),
                ('discount_total', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField()),
                ('payment', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cashless', 'Cashless')], max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionCashierBooks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cashier_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashier_books.cashierbook')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_book_transactions', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_cashier_books',
            },
        ),
        migrations.CreateModel(
            name='TransactionCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_discount_value', models.BigIntegerField(blank=True, null=True)),
                ('item_voucher_value', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(default=1)),
                ('coupon_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coupons.couponcode')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_coupons',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.BigIntegerField()),
                ('partnership_discount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('amount', models.IntegerField()),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='products.productsku')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_item',
            },
        ),
    ]
