# Generated by Django 5.2.5 on 2025-12-11 06:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('sub_total', models.BigIntegerField()),
                ('discount_total', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField()),
                ('payment', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cashless', 'Cashless')], max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.BigIntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'transaction_item',
            },
        ),
    ]
