# Generated by Django 5.2.5 on 2025-12-05 16:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('sub_total', models.BigIntegerField()),
                ('discount_total', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField()),
                ('payment', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cashless', 'Cashless')], max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.BigIntegerField()),
                ('amount', models.IntegerField()),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='products.productsku')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_item',
            },
        ),
    ]
