# Generated by Django 5.2.9 on 2026-01-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='partnership_discount',
            new_name='supplier_discount',
        ),
    ]
