# Generated by Django 5.2.5 on 2025-12-27 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coupons.couponcode')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_coupon',
            },
        ),
    ]
