# Generated by Django 5.2.5 on 2025-12-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactioncoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncoupon',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='transactioncoupon',
            table='transaction_coupons',
        ),
    ]
