# Generated by Django 5.2.9 on 2026-01-03 08:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('payout', models.CharField(choices=[('cash', 'Cash'), ('partnership', 'Partnership')], max_length=20)),
                ('rejection_message', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting_approval', 'Waiting Approval'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='PoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.BigIntegerField()),
                ('amounts', models.IntegerField()),
                ('supplier_discount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remain_stock', models.IntegerField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('none', 'None'), ('partial', 'Partial'), ('completed', 'Completed')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
            ],
            options={
                'db_table': 'po_items',
            },
        ),
    ]
