# Generated by Django 5.2.9 on 2026-01-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='payout',
            new_name='payment_option',
        ),
    ]
