# Generated by Django 5.2.5 on 2025-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
