# Generated by Django 5.2.9 on 2026-01-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='remain_stock',
        ),
        migrations.RemoveField(
            model_name='poitem',
            name='return_status',
        ),
    ]
