# Generated by Django 5.2.5 on 2025-11-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_alter_purchaseorder_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting_approval', 'Waiting Approval'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20),
        ),
    ]
