# Generated by Django 5.2.5 on 2025-12-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_deleted',
        ),
    ]
