# Generated by Django 5.2.9 on 2026-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='payout',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('partnership', 'Partnership')], max_length=20, null=True),
        ),
    ]
