# Generated by Django 5.2.5 on 2025-12-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsku_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
    ]
