# Generated by Django 5.2.9 on 2026-01-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsku_payout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsku',
            old_name='payout',
            new_name='payment_option',
        ),
    ]
