# Generated by Django 5.2.9 on 2026-01-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_payout_productsku_payment_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsku',
            old_name='partnership_discount',
            new_name='supplier_discount',
        ),
    ]
